import { existsSync, readdirSync, readFileSync } from "node:fs";
import { join, resolve } from "node:path";
import { converter, formatHex, parse } from "culori";
import { describe, expect, it } from "vitest";

/**
 * Static invariants for the installable/PWA layer: the manifest, the icons, the service
 * worker, the document `<head>` that wires them, and the browser half of push.
 *
 * WHY THIS FILE EXISTS
 * --------------------
 * This is the layer that *looks* finished and was not. `public/` held two manifests with two
 * different names and three different colours, `public/sw.js` was never registered by
 * anything, its precache list pointed at a URL that does not exist, and the one caller that
 * awaited it (`notifications-client.tsx`) hung on `serviceWorker.ready` forever after burning
 * the user's notification permission. Every one of those was invisible to `tsc`, to the
 * 196 unit tests, and to a browser preview — because nothing in the repository reads these
 * files, and a PWA's configuration is only evaluated by an OS launcher.
 *
 * So the rules below are the joins that no compiler covers: manifest ↔ files on disk,
 * declared icon sizes ↔ actual PNG bytes, palette tokens ↔ `theme_color`, service worker ↔
 * the payload its sender produces, and "documented as wired" ↔ "actually referenced".
 *
 * The artefacts are generated by `pnpm icons:build` from `src/styles.css` and
 * `public/logo-square.svg`; running it is the fix for most failures here.
 */
const ROOT = resolve(__dirname, "../..");
/** The only page this app may show offline: static, and it holds no user data. */
const OFFLINE_URL = "/offline.html";
const PUBLIC = join(ROOT, "public");
const read = (p: string) => readFileSync(p, "utf8");
const manifest = JSON.parse(read(join(PUBLIC, "manifest.webmanifest"))) as {
	name: string;
	short_name: string;
	description: string;
	start_url: string;
	scope: string;
	display: string;
	background_color: string;
	theme_color: string;
	icons: { src: string; sizes: string; type: string; purpose?: string }[];
	shortcuts: { name: string; url: string }[];
};
/** Comments removed: prose about a defect must neither satisfy a rule nor fail one. */
const stripComments = (src: string) =>
	src.replace(/\/\*[\s\S]*?\*\//g, "").replace(/(^|[^:])\/\/[^\n]*/g, "$1");
const swProse = read(join(PUBLIC, "sw.js"));
const sw = stripComments(swProse);
const root = read(join(ROOT, "src/routes/__root.tsx"));

/** The `@theme` block's token, converted the same way the generator converts it. */
function tokenHex(
	name: string,
	css = read(join(ROOT, "src/styles.css")),
): string {
	const m = new RegExp(`--color-${name}:\\s*([^;]+);`).exec(css);
	if (!m) throw new Error(`--color-${name} not found in src/styles.css`);
	const rgb = converter("rgb")(parse(m[1]));
	if (!rgb) throw new Error(`could not convert --color-${name}: ${m[1]}`);
	return formatHex({ mode: "rgb", r: rgb.r, g: rgb.g, b: rgb.b });
}

/** PNG width/height straight out of the IHDR chunk — the manifest's `sizes` must be true. */
function pngSize(path: string): { width: number; height: number } {
	const buf = readFileSync(path);
	expect(buf.subarray(0, 8)).toEqual(
		Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]),
	);
	return { width: buf.readUInt32BE(16), height: buf.readUInt32BE(20) };
}

/** Everything that can reference a `public/` file, as one haystack. */
function haystack(): string {
	const parts: string[] = [];
	const walk = (dir: string) => {
		for (const entry of readdirSync(dir, { withFileTypes: true })) {
			const p = join(dir, entry.name);
			if (entry.isDirectory()) walk(p);
			else if (/\.(?:ts|tsx|css|html|js|mjs|json)$/.test(entry.name)) {
				parts.push(read(p));
			}
		}
	};
	walk(join(ROOT, "src"));
	walk(join(ROOT, "supabase/functions"));
	parts.push(read(join(PUBLIC, "manifest.webmanifest")), swProse);
	for (const extra of ["e2e/app.spec.ts", "Dockerfile"]) {
		if (existsSync(join(ROOT, extra))) parts.push(read(join(ROOT, extra)));
	}
	return parts.join("\n");
}

function publicFiles(dir = PUBLIC, prefix = ""): string[] {
	const out: string[] = [];
	for (const entry of readdirSync(dir, { withFileTypes: true })) {
		const rel = `${prefix}${entry.name}`;
		if (entry.isDirectory())
			out.push(...publicFiles(join(dir, entry.name), `${rel}/`));
		else out.push(rel);
	}
	return out;
}

describe("web manifest", () => {
	it("references only head assets that exist under public/", () => {
		// Every `href`/`src` the document head advertises must resolve, because a missing
		// one is invisible to the build, to `tsc` and to a desktop browser: `/apple-touch-icon-180.png`
		// 404'd for as long as the generator wrote that file to the repo root instead of
		// `public/`, and only iOS noticed, by showing a screenshot of the page as the icon.
		const refs = [...root.matchAll(/(?:href|src):\s*"((?:\/[^"]+)+)"/g)].map(
			(m) => m[1],
		);
		expect(refs.length).toBeGreaterThanOrEqual(4);
		for (const ref of refs) {
			if (/^https?:|^\/\//.test(ref)) continue;
			const file = join(PUBLIC, ref.replace(/^\//, ""));
			expect(existsSync(file), `${ref} is not served from public/`).toBe(true);
		}
	});

	it("has exactly one manifest, and links it from the document", () => {
		// Two manifests is two names for the app in the OS UI. The old `manifest.json` said
		// "FYKING" with a `#d4af37` theme colour; `manifest.webmanifest` said "FYK".
		expect(existsSync(join(PUBLIC, "manifest.json"))).toBe(false);
		expect(root).toContain('rel: "manifest"');
		expect(root).toContain("viewport-fit=cover");
		expect(root).toContain('src: "/theme-init.js"');
		expect(root).toContain("/manifest.webmanifest");
	});

	it("uses the app's real palette, in the manifest and in the theme-color metas", () => {
		// Every one of these values used to be a hand-copied hex that no token defines
		// (`#0B0D11`, `#000000`, `#d4af37`, `#EDB219`), so the status-bar paint and the
		// install splash disagreed with the design system on every device.
		const dark = tokenHex("background");
		const light = tokenHex(
			"background",
			(() => {
				const css = read(join(ROOT, "src/styles.css"));
				const block = /\.light\s*\{([\s\S]*?)\n\}/.exec(css)?.[1] ?? "";
				if (!block) throw new Error("no `.light` block in src/styles.css");
				return block;
			})(),
		);
		expect(manifest.theme_color).toBe(dark);
		expect(manifest.background_color).toBe(dark);
		// The base meta (no-JS, and what SSR paints) carries the dark value…
		expect(root).toContain(`content: "${dark}"`);
		// …and the light value lives in the pre-paint script, because Start de-duplicates
		// `meta[name]` and a dark+light *pair* here silently collapses to whichever is later.
		// Asserting that split is the point: "the light theme-colour is missing" is otherwise
		// invisible until somebody opens the app in light mode and the status bar stays black.
		const themeInit = readFileSync(join(PUBLIC, "theme-init.js"), "utf8");
		expect(themeInit).toContain(`light: "${light}"`);
		expect(themeInit).toContain(`dark: "${dark}"`);
		// A second viewport meta means the browser may pick the one without `viewport-fit`.
		expect((root.match(/name: "viewport"/g) ?? []).length).toBe(1);
	});

	it("names the same app as the document title", () => {
		expect(manifest.name).toBe("FYK — Find Your King");
		expect(root).toContain(`title: "${manifest.name}"`);
		expect(manifest.short_name).toBe(manifest.name.split(" — ")[0]);
		expect(manifest.short_name.length).toBeLessThanOrEqual(12);
		expect(manifest.description).toBe(
			/name: "description", content: "([^"]+)"/.exec(root)?.[1],
		);
	});

	it("ships every icon it declares, at the size it declares", () => {
		// The previous manifest pointed at `/icons/icon-192.png` and `/icons/icon-512.png`,
		// and `public/icons/` contained only SVGs: installability is checked against a real
		// PNG by every browser that offers it, so the whole feature was one missing file away
		// from never appearing.
		expect(manifest.icons.length).toBeGreaterThanOrEqual(3);
		for (const icon of manifest.icons) {
			const file = join(PUBLIC, icon.src.replace(/^\//, ""));
			expect(existsSync(file), `${icon.src} does not exist`).toBe(true);
			const { width, height } = pngSize(file);
			expect(`${width}x${height}`, `${icon.src} is not ${icon.sizes}`).toBe(
				icon.sizes,
			);
		}
		expect(manifest.icons.some((i) => i.purpose?.includes("maskable"))).toBe(
			true,
		);
	});

	it("points its entry points at routes that exist", () => {
		const routeExists = (url: string) => {
			const path = url.replace(/^\//, "").replace(/\/$/, "");
			const flat = join(ROOT, "src/routes", `${path || "index"}.tsx`);
			const nested = join(ROOT, "src/routes", path, "index.tsx");
			return existsSync(flat) || existsSync(nested);
		};
		expect(manifest.start_url).toBe("/");
		expect(manifest.scope).toBe("/");
		expect(manifest.display).toBe("standalone");
		for (const shortcut of manifest.shortcuts) {
			expect(
				routeExists(shortcut.url),
				`shortcut ${shortcut.url} has no route`,
			).toBe(true);
		}
	});
});

describe("service worker", () => {
	it("is registered absolutely, once, and only in a production build", () => {
		// `"./sw.js"` + `scope: "./"` resolved against the *document* URL, so any route
		// rendered at a trailing-slash path looked for the worker beside itself and 404'd;
		// and registering a caching worker in front of Vite's dev server makes HMR
		// undebuggable, so dev must decline out loud rather than half-work.
		const persist = read(join(ROOT, "src/lib/persist.ts"));
		expect(persist).toContain('register("/sw.js"');
		expect(persist).toContain('scope: "/"');
		expect(persist).toContain("import.meta.env.PROD");
		expect(persist).toContain("disabled-in-dev");
	});

	it("precaches only files that exist", () => {
		// `STATIC_ASSETS = ["/", "/offline"]` looked reasonable and was fatal twice over:
		// there is no `/offline` route (the file is `/offline.html`), so `cache.addAll`
		// rejected, `install` failed and the worker never activated — and precaching `/`
		// would have cached one person's `private, no-store` document for everybody.
		const precached = /const PRECACHE = \[([\s\S]*?)\];/.exec(sw)?.[1] ?? "";
		const urls = [...precached.matchAll(/"([^"]+)"/g)].map((m) => m[1]);
		expect(urls.length).toBeGreaterThanOrEqual(3);
		for (const url of urls) {
			expect(
				existsSync(join(PUBLIC, url.replace(/^\//, ""))),
				`${url} is not a file in public/`,
			).toBe(true);
		}
		expect(precached).not.toMatch(/"\/"/);
	});

	it("never serves a cached response for an API call or a document", () => {
		// The old body was `caches.match(event.request).then(cached => cached || fetch…)`,
		// i.e. cache-first for *everything*: wallet balances, notification lists and the
		// signed-in HTML document included.
		expect(sw).not.toContain("caches.match(event.request)");
		expect(sw).toContain('startsWith("/api/")');
		expect(sw).toContain('request.mode === "navigate"');
		expect(sw).toContain(OFFLINE_URL);
		// `cache.put` may only happen inside the static-asset helper.
		const putSites = [...sw.matchAll(/cache\.put\(/g)].length;
		expect(putSites).toBe(1);
		expect(/async function fromStaticCache[\s\S]*?cache\.put\(/.test(sw)).toBe(
			true,
		);
	});

	it("handles the push events the subscription depends on", () => {
		// A subscription is accepted by the browser even when nothing listens for `push`,
		// which is how push can be "enabled" and silently deliver nothing forever.
		for (const event of [
			'"push"',
			'"notificationclick"',
			'"notificationclose"',
			'"pushsubscriptionchange"',
		]) {
			expect(sw, `sw.js must handle ${event}`).toContain(
				`addEventListener(${event}`,
			);
		}
		expect(sw).toContain("showNotification");
	});

	it("deep-links with the same filter the inbox uses", () => {
		// The href in a payload ends up as the URL an installed app opens, so it gets the
		// identical treatment `safeDeepLink()` gives a database value before it reaches an
		// `<a href>`. Shared source text, shared rule: one file changing is a test failure.
		const client = read(
			join(ROOT, "src/components/notifications/notifications-client.tsx"),
		);
		const re = /export const UNSAFE_SCHEME = (\S[^;]*);/.exec(client);
		expect(
			re,
			"safeDeepLink's filter is no longer `export const UNSAFE_SCHEME`",
		).toBeTruthy();
		const source = re?.[1] ?? "";
		expect(source).toContain("[a-z0-9+.-]");
		expect(sw).toContain(source);
		expect(sw).toContain("url.origin === self.location.origin");
	});
});

describe("device wiring", () => {
	it("has an unsubscribe on both sides of the network boundary", () => {
		// `PushSubscription.unsubscribe()` only stops *this browser*. Without a server-side
		// delete, "turn off notifications" leaves an endpoint the user cannot reach sitting
		// in `push_subscriptions` — on an app of this kind, a safety hole, not a leak.
		const route = read(join(ROOT, "src/routes/api/push/subscribe.ts"));
		expect(route).toContain("DELETE: withSecurity");
		expect(route).toContain("pushSubscriptions.userId, user.id");
		const client = read(join(ROOT, "src/lib/push.ts"));
		expect(client).toContain('method: "DELETE"');
		expect(client).toContain("?endpoint=");
	});

	it("never requests notification permission on mount", () => {
		// The defect that prompted the whole layer: `registerPushSubscription()` asked for
		// permission and then awaited a worker nobody had registered. A prompt may only come
		// from `enablePush()`, which is called by a click.
		const client = read(
			join(ROOT, "src/components/notifications/notifications-client.tsx"),
		);
		expect(client).not.toContain("Notification.requestPermission");
		expect(client).toContain("<PushRow />");
		const push = read(join(ROOT, "src/lib/push.ts"));
		const at = push.indexOf("requestPermission");
		expect(at).toBeGreaterThan(-1);
		expect(push.slice(0, at)).toContain("export async function enablePush");
		expect(push.slice(0, at).indexOf("enablePush")).toBeGreaterThan(-1);
	});

	it("documents every environment variable an edge function reads", () => {
		// `notify` and `cron-cleanup` now *refuse to run* without their secrets; a required
		// env var that appears in no `.env.example` is how that becomes a mystery at deploy
		// time rather than a step in the README.
		const env = read(join(ROOT, ".env.example"));
		const names = new Set<string>();
		for (const file of readdirSync(join(ROOT, "supabase/functions"), {
			withFileTypes: true,
		})) {
			if (!file.isDirectory()) continue;
			const p = join(ROOT, "supabase/functions", file.name, "index.ts");
			if (!existsSync(p)) continue;
			for (const m of read(p).matchAll(/Deno\.env\.get\("([A-Z0-9_]+)"\)/g)) {
				names.add(m[1]);
			}
		}
		expect(names.size).toBeGreaterThan(4);
		const missing = [...names].filter((n) => !env.includes(n));
		expect(missing).toEqual([]);
	});

	it("leaves no asset in public/ that nothing references", () => {
		// Orphan files are how this layer drifted: `theme-init.js` existed, was correct, and
		// was loaded by nobody, so light mode flashed dark on every load for as long as the
		// file had been there.
		const needle = haystack();
		// `logo-horizontal.svg` is a brand asset the marketing page may pick up; the demo
		// photos are referenced by basename from `src/data/demo-guitars.ts`.
		const ALLOWED_ORPHANS = new Set(["logo-horizontal.svg"]);
		const orphans = publicFiles(PUBLIC).filter((rel) => {
			if (ALLOWED_ORPHANS.has(rel)) return false;
			return !needle.includes(`/${rel}`) && !needle.includes(rel);
		});
		expect(orphans).toEqual([]);
	});
});
