# ═══════════════════════════════════════════════════════════════════════════════
# FYK Consolidated — build + runtime (TanStack Start on Vite)
# ═══════════════════════════════════════════════════════════════════════════════
# Notes on the previous version of this file:
#   * `HEALTHCHECK CMD curl -f http://localhost:3000/health` probed a route that
#     does not exist (`/api/health` does), so every container was marked
#     unhealthy and an orchestrator restarted it forever.
#   * `CMD ["node", "dist/server.js"]` could not work: the SSR build exports a
#     `fetch` handler (`createStartHandler`) and starts no listener, so the
#     process exited immediately after the build succeeded. `vite preview` is
#     what actually serves `dist/client` + the SSR/API handler.
#   * `npx prisma generate` at build time needs network access to
#     binaries.prisma.sh for the engine download and a valid DATABASE_URL for the
#     Prisma config; the API no longer uses Prisma, so the step is gone.
#   * VITE_* variables are inlined at BUILD time, so they must be build args —
#     and only public values may ever be passed that way.

# ───────────────────────────── Stage 1: build ────────────────────────────────
FROM node:20-alpine AS builder
WORKDIR /app

ENV CI=true
RUN corepack enable

# Dependency layer first: unchanged lockfile ⇒ cached install.
COPY package.json pnpm-lock.yaml ./
RUN pnpm install --frozen-lockfile

COPY . .

# Public, inlined config. Never pass a secret as a build arg.
ARG VITE_SUPABASE_URL
ARG VITE_SUPABASE_ANON_KEY
ARG VITE_MAPBOX_ACCESS_TOKEN
ARG VITE_APP_URL=https://app.fyk.example
ARG VITE_APP_ENV=production
ARG VITE_POSTHOG_KEY=
ARG VITE_ANALYTICS_ENABLED=false

ENV NODE_ENV=production \
    VITE_SUPABASE_URL=$VITE_SUPABASE_URL \
    VITE_SUPABASE_ANON_KEY=$VITE_SUPABASE_ANON_KEY \
    VITE_MAPBOX_ACCESS_TOKEN=$VITE_MAPBOX_ACCESS_TOKEN \
    VITE_APP_URL=$VITE_APP_URL \
    VITE_APP_ENV=$VITE_APP_ENV \
    VITE_POSTHOG_KEY=$VITE_POSTHOG_KEY \
    VITE_ANALYTICS_ENABLED=$VITE_ANALYTICS_ENABLED

# Route types are generated by the router plugin during `vite build`; run the
# generator first so the build is reproducible from a clean checkout.
RUN pnpm generate-routes && pnpm build

# ──────────────────────────── Stage 2: runtime ───────────────────────────────
FROM node:20-alpine AS runner
WORKDIR /app
RUN apk add --no-cache curl

# `vite preview` is the server here, so Vite and the config files it reads must
# exist at runtime; the SSR bundle itself is self-contained in dist/.
COPY --from=builder /app/package.json ./
COPY --from=builder /app/pnpm-lock.yaml ./
COPY --from=builder /app/vite.config.ts ./
COPY --from=builder /app/tsconfig.json ./
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/dist ./dist

RUN addgroup -g 1001 -S fyk && adduser -S fyk -u 1001 -G fyk
USER fyk

ENV NODE_ENV=production \
    HOST=0.0.0.0 \
    PORT=3000 \
    # Read at request time by #/db and #/lib/supabase-auth.server.
    DATABASE_URL="" \
    SUPABASE_URL="" \
    SUPABASE_ANON_KEY="" \
    SUPABASE_JWT_SECRET=""

EXPOSE 3000

# Liveness only (shallow): a database outage must not make the orchestrator kill
# a container that can still render the site. Use `?deep=1` for a readiness
# probe that answers 503 when Postgres is unreachable.
HEALTHCHECK --interval=30s --timeout=5s --start-period=20s --retries=3 \
  CMD curl -fsS "http://127.0.0.1:${PORT}/api/health" || exit 1

# `--host` is required: the default binds to localhost, which is unreachable
# from outside the container.
CMD ["sh", "-c", "node_modules/.bin/vite preview --host \"$HOST\" --port \"$PORT\""]
