import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
import webPush from "https://esm.sh/web-push@3.6.7";

// ---------------------------------------------------------------------------
// Push delivery. Invoked by Postgres, never by a browser.
//
// The caller is `public.enqueue_push_notification()` (see
// `supabase/migrations/0023_optimizations_reordered.sql` and
// `0025_push_delivery_secret.sql`), which fires on every insert into
// `public.notifications` and POSTs the row's own `{userId,title,body,href}`.
// That has three consequences this file has to honour:
//
//  1. **The inbox row already exists.** The trigger is on *that* insert, so the
//     notification is the record and a push is a copy of it. Inserting again from
//     here (which the first version of this function did, as `type: "push"`) both
//     violates `notifications_type_check` — which lists every type the app writes and
//     `push` is not a type anyone chooses to display, it is a transport — and would
//     re-fire the same trigger, recursing until the stack depth guard aborted the
//     transaction. It is deleted, not "made safe".
//  2. **There is no user JWT in this call path.** Supabase defaults every function to
//     `verify_jwt = true`, and a `pg_net` request carries no `Authorization` header, so
//     the honest configuration is `verify_jwt = false` (see `supabase/config.toml`)
//     *plus* a shared secret, because a function that can send a notification to any
//     user's lock screen from an unauthenticated URL is a phishing primitive: the
//     payload text is attacker-chosen and it arrives branded as the app. `x-fyk-push-token`
//     must equal `PUSH_INTERNAL_TOKEN`, compared in constant time, and there is no
//     default: unset secret means push delivery is off, not push delivery is open.
//  3. **CORS is not a security boundary here and is not pretended to be.** The response
//     carries no `Access-Control-Allow-Origin` at all, so a random web page cannot read
//     the result, and the header check is what actually stops the request.
// ---------------------------------------------------------------------------

// Configure VAPID credentials once at module level.
// These must be set as Supabase Edge Function secrets:
//   VITE_VAPID_PUBLIC_KEY  – base64-url public key (generated by `pnpm push:vapid-keys`)
//   VAPID_PRIVATE_KEY      – base64-url private key
//   VAPID_SUBJECT          – contact email/url, e.g. "mailto:admin@example.com"
//   PUSH_INTERNAL_TOKEN    – shared with Postgres via `fyk.push_notify_token`
const VAPID_PRIVATE_KEY = Deno.env.get("VAPID_PRIVATE_KEY") ?? "";
const VAPID_SUBJECT = Deno.env.get("VAPID_SUBJECT") ?? "mailto:noreply@fyk.app";
const INTERNAL_TOKEN = Deno.env.get("PUSH_INTERNAL_TOKEN") ?? "";

if (VAPID_PRIVATE_KEY) {
  webPush.setVapidDetails(
    VAPID_SUBJECT,
    Deno.env.get("VITE_VAPID_PUBLIC_KEY") ?? "",
    VAPID_PRIVATE_KEY,
  );
}

/** Constant-time string comparison: a 401 must not leak how much of a guess was right. */
function timingSafeEqual(a: string, b: string): boolean {
  if (a.length !== b.length) return false;
  let diff = 0;
  for (let i = 0; i < a.length; i++) {
    diff |= a.charCodeAt(i) ^ b.charCodeAt(i);
  }
  return diff === 0;
}

function reject(status: number, error: string): Response {
  return new Response(JSON.stringify({ error }), {
    status,
    headers: { "Content-Type": "application/json", "Cache-Control": "no-store" },
  });
}

serve(async (req) => {
  if (req.method === "OPTIONS") {
    // Preflight for a `content-type: application/json` POST. No
    // `Access-Control-Allow-Origin` is returned, so a browser on another origin cannot
    // call this at all; Postgres and a scheduler are not browsers and do not care.
    return new Response(null, { status: 204 });
  }

  if (req.method !== "POST") {
    return reject(405, "method not allowed");
  }

  // Order matters: authenticate before parsing a body or touching the network.
  if (!INTERNAL_TOKEN) {
    console.error("PUSH_INTERNAL_TOKEN is not set – refusing to accept delivery requests");
    return reject(503, "Push delivery not configured");
  }
  if (!timingSafeEqual(req.headers.get("x-fyk-push-token") ?? "", INTERNAL_TOKEN)) {
    return reject(401, "Invalid delivery token");
  }

  let payload: { userId?: unknown; title?: unknown; body?: unknown; href?: unknown };
  try {
    // The trigger sends a few hundred bytes; anything larger is not this app's caller.
    const text = await req.text();
    if (text.length > 16 * 1024) return reject(413, "payload too large");
    payload = JSON.parse(text);
  } catch {
    return reject(400, "Invalid JSON body");
  }

  const { userId, title } = payload;
  if (typeof userId !== "string" || !userId || typeof title !== "string" || !title) {
    return reject(400, "userId and title are required");
  }
  const body = typeof payload.body === "string" ? payload.body : "";
  const href = typeof payload.href === "string" ? payload.href : "";
  if (title.length > 200 || body.length > 600) {
    // A notification's visible text is capped in the API routes that create the row;
    // repeating the cap here keeps a direct SQL insert from producing a payload the
    // service providers reject.
    return reject(422, "title and body are too long");
  }

  // Early exit if VAPID keys are not configured
  if (!VAPID_PRIVATE_KEY) {
    console.error("VAPID_PRIVATE_KEY is not set – cannot send push");
    return reject(503, "Push notifications not configured");
  }

  const supabase = createClient(
    Deno.env.get("SUPABASE_URL") ?? "",
    Deno.env.get("SUPABASE_SERVICE_ROLE_KEY") ?? "",
  );

  // Get all push subscriptions for this user
  const { data: subscriptions, error: subError } = await supabase
    .from("push_subscriptions")
    .select("id, endpoint, p256dh, auth")
    .eq("user_id", userId);

  if (subError) {
    console.error("Error fetching subscriptions:", subError.message);
    return reject(500, "Could not read subscriptions");
  }

  if (!subscriptions?.length) {
    return new Response(JSON.stringify({ sent: 0, failed: 0, removed: 0 }), {
      headers: { "Content-Type": "application/json", "Cache-Control": "no-store" },
    });
  }

  // Build the push payload. This is the *contract with the service worker*:
  // `public/sw.js` parses exactly `{title, body, href}` and nothing else, and its
  // static guard test asserts that pairing.
  const pushPayload = JSON.stringify({ title, body, href });

  let sent = 0;
  let failed = 0;
  let removed = 0;

  for (const sub of subscriptions) {
    // Map DB row to the PushSubscription shape web-push expects
    const pushSubscription = {
      endpoint: sub.endpoint,
      keys: {
        p256dh: sub.p256dh,
        auth: sub.auth,
      },
    };

    try {
      await webPush.sendNotification(pushSubscription, pushPayload);
      sent++;
    } catch (err) {
      failed++;
      const statusCode = (err as { statusCode?: number; status?: number }).statusCode ||
        (err as { status?: number }).status || 0;

      // 404 / 410 = subscription has expired or been unsubscribed – remove it, or the
      // row keeps failing forever and the per-user cap fills with dead endpoints.
      if (statusCode === 404 || statusCode === 410) {
        await supabase.from("push_subscriptions").delete().eq("id", sub.id);
        removed++;
      } else {
        console.error(
          `Push failed for ${sub.endpoint.slice(0, 60)}... (status ${statusCode}):`,
          (err as Error).message,
        );
      }
    }
  }

  return new Response(JSON.stringify({ sent, failed, removed }), {
    headers: { "Content-Type": "application/json", "Cache-Control": "no-store" },
  });
});
