/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ApiSplatRouteImport } from './routes/api/$'
import { Route as BoardIndexRouteImport } from './routes/board/index'
import { Route as ChatIndexRouteImport } from './routes/chat/index'
import { Route as EventsIndexRouteImport } from './routes/events/index'
import { Route as GridIndexRouteImport } from './routes/grid/index'
import { Route as NotificationsIndexRouteImport } from './routes/notifications/index'
import { Route as SafetyIndexRouteImport } from './routes/safety/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as AuthCallbackIndexRouteImport } from './routes/auth/callback/index'
import { Route as ChatConversationIdIndexRouteImport } from './routes/chat/$conversationId/index'
import { Route as ProfileProfileIdIndexRouteImport } from './routes/profile/$profileId/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardIndexRoute = BoardIndexRouteImport.update({
  id: '/board/',
  path: '/board/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIndexRoute = ChatIndexRouteImport.update({
  id: '/chat/',
  path: '/chat/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const GridIndexRoute = GridIndexRouteImport.update({
  id: '/grid/',
  path: '/grid/',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsIndexRoute = NotificationsIndexRouteImport.update({
  id: '/notifications/',
  path: '/notifications/',
  getParentRoute: () => rootRouteImport,
} as any)
const SafetyIndexRoute = SafetyIndexRouteImport.update({
  id: '/safety/',
  path: '/safety/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackIndexRoute = AuthCallbackIndexRouteImport.update({
  id: '/auth/callback/',
  path: '/auth/callback/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatConversationIdIndexRoute = ChatConversationIdIndexRouteImport.update({
  id: '/chat/$conversationId/',
  path: '/chat/$conversationId/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileProfileIdIndexRoute = ProfileProfileIdIndexRouteImport.update({
  id: '/profile/$profileId/',
  path: '/profile/$profileId/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/$': typeof ApiSplatRoute
  '/admin/': typeof AdminIndexRoute
  '/board/': typeof BoardIndexRoute
  '/chat/': typeof ChatIndexRoute
  '/events/': typeof EventsIndexRoute
  '/grid/': typeof GridIndexRoute
  '/notifications/': typeof NotificationsIndexRoute
  '/safety/': typeof SafetyIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/auth/callback/': typeof AuthCallbackIndexRoute
  '/chat/$conversationId/': typeof ChatConversationIdIndexRoute
  '/profile/$profileId/': typeof ProfileProfileIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/$': typeof ApiSplatRoute
  '/admin': typeof AdminIndexRoute
  '/board': typeof BoardIndexRoute
  '/chat': typeof ChatIndexRoute
  '/events': typeof EventsIndexRoute
  '/grid': typeof GridIndexRoute
  '/notifications': typeof NotificationsIndexRoute
  '/safety': typeof SafetyIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/auth/callback': typeof AuthCallbackIndexRoute
  '/chat/$conversationId': typeof ChatConversationIdIndexRoute
  '/profile/$profileId': typeof ProfileProfileIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/$': typeof ApiSplatRoute
  '/admin/': typeof AdminIndexRoute
  '/board/': typeof BoardIndexRoute
  '/chat/': typeof ChatIndexRoute
  '/events/': typeof EventsIndexRoute
  '/grid/': typeof GridIndexRoute
  '/notifications/': typeof NotificationsIndexRoute
  '/safety/': typeof SafetyIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/auth/callback/': typeof AuthCallbackIndexRoute
  '/chat/$conversationId/': typeof ChatConversationIdIndexRoute
  '/profile/$profileId/': typeof ProfileProfileIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/$'
    | '/admin/'
    | '/board/'
    | '/chat/'
    | '/events/'
    | '/grid/'
    | '/notifications/'
    | '/safety/'
    | '/settings/'
    | '/auth/callback/'
    | '/chat/$conversationId/'
    | '/profile/$profileId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/$'
    | '/admin'
    | '/board'
    | '/chat'
    | '/events'
    | '/grid'
    | '/notifications'
    | '/safety'
    | '/settings'
    | '/auth/callback'
    | '/chat/$conversationId'
    | '/profile/$profileId'
  id:
    | '__root__'
    | '/'
    | '/api/$'
    | '/admin/'
    | '/board/'
    | '/chat/'
    | '/events/'
    | '/grid/'
    | '/notifications/'
    | '/safety/'
    | '/settings/'
    | '/auth/callback/'
    | '/chat/$conversationId/'
    | '/profile/$profileId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiSplatRoute: typeof ApiSplatRoute
  AdminIndexRoute: typeof AdminIndexRoute
  BoardIndexRoute: typeof BoardIndexRoute
  ChatIndexRoute: typeof ChatIndexRoute
  EventsIndexRoute: typeof EventsIndexRoute
  GridIndexRoute: typeof GridIndexRoute
  NotificationsIndexRoute: typeof NotificationsIndexRoute
  SafetyIndexRoute: typeof SafetyIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  AuthCallbackIndexRoute: typeof AuthCallbackIndexRoute
  ChatConversationIdIndexRoute: typeof ChatConversationIdIndexRoute
  ProfileProfileIdIndexRoute: typeof ProfileProfileIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/board/': {
      id: '/board/'
      path: '/board'
      fullPath: '/board/'
      preLoaderRoute: typeof BoardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/': {
      id: '/chat/'
      path: '/chat'
      fullPath: '/chat/'
      preLoaderRoute: typeof ChatIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grid/': {
      id: '/grid/'
      path: '/grid'
      fullPath: '/grid/'
      preLoaderRoute: typeof GridIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications/': {
      id: '/notifications/'
      path: '/notifications'
      fullPath: '/notifications/'
      preLoaderRoute: typeof NotificationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/safety/': {
      id: '/safety/'
      path: '/safety'
      fullPath: '/safety/'
      preLoaderRoute: typeof SafetyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback/': {
      id: '/auth/callback/'
      path: '/auth/callback'
      fullPath: '/auth/callback/'
      preLoaderRoute: typeof AuthCallbackIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$conversationId/': {
      id: '/chat/$conversationId/'
      path: '/chat/$conversationId'
      fullPath: '/chat/$conversationId/'
      preLoaderRoute: typeof ChatConversationIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$profileId/': {
      id: '/profile/$profileId/'
      path: '/profile/$profileId'
      fullPath: '/profile/$profileId/'
      preLoaderRoute: typeof ProfileProfileIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiSplatRoute: ApiSplatRoute,
  AdminIndexRoute: AdminIndexRoute,
  BoardIndexRoute: BoardIndexRoute,
  ChatIndexRoute: ChatIndexRoute,
  EventsIndexRoute: EventsIndexRoute,
  GridIndexRoute: GridIndexRoute,
  NotificationsIndexRoute: NotificationsIndexRoute,
  SafetyIndexRoute: SafetyIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  AuthCallbackIndexRoute: AuthCallbackIndexRoute,
  ChatConversationIdIndexRoute: ChatConversationIdIndexRoute,
  ProfileProfileIdIndexRoute: ProfileProfileIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
